name: Automated tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  node:
    name: Node ${{ matrix.node_version }}

    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 12
          - lts/*
          - current

    runs-on: ubuntu-latest
    
    # Allow failues for most recent Node release
    continue-on-error: ${{ matrix.node_version == 'current' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm

      - name: Install
        run: npm clean-install

      - name: Test
        run: npm run test


  docker:
    name: Docker (lts-alpine)

    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image from Dockerfile
        run: docker build --tag dr4ft-app .

      - name: Run container from image
        run: docker run -d -p 1337:1337 --name dr4ft dr4ft-app
      
      # TODO: This needs probably some tweaking or can be tested further
      - name: Access Docker container
        run: wget http://localhost:1337

      - name: Show information
        run: |
          docker --version
          echo
          docker images
          echo
          docker ps -a
          echo
          echo "Node version (dr4ft container)"
          docker run node:lts-alpine node --version
          

  lint:
    name: ESLint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm clean-install --ignore-scripts

      - name: Run ESLint
        run: |
          node --version
          echo
          npm run lint
